# Autogenerated wrapper script for S2Geometry_jll for x86_64-apple-darwin
export libs2

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("S2Geometry")
JLLWrappers.@declare_library_product(libs2, "@rpath/libs2.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libs2,
        "lib/libs2.0.10.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
